import Head from "next/head";
import ContentCard from "@components/ContentCard";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ContentCard />
        {/* 로그인 확인용 */}
        <h2>{data?.user?.name}</h2>
        {data?.user ? (
          <button type="button" onClick={() => signOut()}>
            Google Logout
          </button>
        ) : (
          <button type="button" onClick={() => signIn("google")}>
            Google Login
          </button>
        )}
      </main>
    </>
  );
}
